language: python

#os:
#  - linux

# name for miniconda files in https://repo.continuum.io/miniconda
env: MINI_ARCH="x86_64"
     MINI="Miniconda3"
     LANG="en_US.UTF-8"
     LC_ALL="en_US.UTF-8"
     
#  # for packages on https://repo.anaconda.com/miniconda/

#  - osx
#  # for packages on https://repo.anaconda.com/miniconda/
#  env: MINI_OS="MacOSX"
#       MINI_ARCH="x86_64"

jobs:
  allow_failures:
    - os:
      - "osx"
      - "windows"
    - python:
      - "3.4"
      - "3.5"
      - "3.6"
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
os: 
  - "linux"
  - "osx"
# - windows
# - osx


  # for packages on https://repo.anaconda.com/miniconda/
#  - "3.6"      # current default Python on Travis CI
#
#   - "2.7"
#   env: MINI=Miniconda2
#  - "3.4"
#  - "3.5"
#   - "2.7"
#  - "3.4"
# - "3.5"
# command to install dependencies
# conda from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html

# brew
before_install:
  - source env.sh
  # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  # https://brew.sh/
  # assume brew is already installed
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then  
      export MINI_OS="MacOSX";
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"; 
      brew update;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      export MINI_OS="Linux";
      sudo apt update; 
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      export MINI_OS="Windows";
    fi

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  # system requirements defined in apt.txt b ut also works for brew
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cat apt.txt | xargs sudo apt-get install; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ;  then cat apt.txt | xargs brew install; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cat apt.txt | xargs choco install; fi
  # download miniconda into $HOME/miniconda
  - wget https://repo.continuum.io/miniconda/${MINI}-latest-${MINI_OS}-${MINI_ARCH}.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # set up: uses information from env.sh
  - python setup.py install 
  # Replace dep1 dep2 ... with your dependencies
  # python=$TRAVIS_PYTHON_VERSION
  - conda env create -n uclgeog --file environment.yml
  - conda activate uclgeog 
  #- conda config --add channels proflewis
  # make the uclgeog codebase
  - python -m pip install --user --upgrade setuptools wheel
  - python setup.py install
  - /bin/bash ./postBuild 
  # sort some edits to the notebook
  - python uclgeog/sort_notebook.py
  - pwd
  - ls
  - cat ${HOME}/.jupyter/jupyter_notebook_config.json
  
# command to run tests
script:
  # this is in test.yml too ... resolve
  - python -c "import uclgeog" || echo "Not done"
