language: python

# name for miniconda files in https://repo.continuum.io/miniconda
env: LANG="en_US.UTF-8"
     LC_ALL="en_US.UTF-8"
     
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - source env.sh
        - env
        - sudo apt update; 
        - pip3 install --upgrade pip
        - cat apt.txt | xargs sudo apt-get install
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - source env.sh
        - env
        - sudo apt update; 
        - pip3 install --upgrade pip
        - cat apt.txt | xargs sudo apt-get install
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - source env.sh
        - pip3 install --upgrade pip
        - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"; 
        - brew update
        - cat apt.txt | xargs brew install
        - curl https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-MaxOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - source env.sh
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -O miniconda.exe
        # https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html
        - start /wait "" miniconda.exe /InstallationType=JustMe /S /D=%UserProfile%\Miniconda3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# conda from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # set up: uses information from env.sh
  - python setup.py install 
  # Replace dep1 dep2 ... with your dependencies
  # python=$TRAVIS_PYTHON_VERSION
  - conda env create -n uclgeog --file environment.yml
  - conda activate uclgeog 
  #- conda config --add channels proflewis
  # make the uclgeog codebase
  - python -m pip install --user --upgrade setuptools wheel
  - python setup.py install
  - /bin/bash ./postBuild 
  # sort some edits to the notebook
  - python uclgeog/sort_notebook.py
  - pwd
  - ls
  - cat ${HOME}/.jupyter/jupyter_notebook_config.json
  
# command to run tests
script:
  # this is in test.yml too ... resolve
  - python -c "import uclgeog" || echo "Not done"
