sudo: required

services:
  - docker

env: 
  LANG:   "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
     
jobs:
  allow_failures:
  - rvm: 1.9.3
    if: branch = master     
     
     
jobs:

  allow_failures:
  - name: "Python 3.8 on Windows"
  - name: "Python 3.7 on macOS"
  - name: "Python 3.8 on macOS"
  
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - source env.sh
        - env
        - sudo apt update; 
        - grep -v '#' < apt.txt | xargs sudo apt-get install
        - wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        # docker prep
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - source env.sh
        - env
        - sudo apt update; 
        - grep -v '#' < apt.txt  | xargs sudo apt-get install
        - wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        # docker prep
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - source env.sh
        - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"; 
        - brew update
        - grep -v '#' < apt.txt | xargs brew install
        - wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - source env.sh
        - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"; 
        - brew update
        - grep -v '#' < apt.txt | xargs brew install
        - wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-MacOSX-x86_64.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        #- source env.sh
        - choco install python --version 3.8.0
        - choco install wget
        - python -m pip install --upgrade pip
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -O miniconda.exe
        # https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html
        - start /wait "" miniconda.exe /InstallationType=JustMe /S /D=%UserProfile%\Miniconda3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# conda from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  # python=$TRAVIS_PYTHON_VERSION
  - conda env create -n uclgeog --file environment.yml
  - conda activate uclgeog 
  #- conda config --add channels proflewis
  # make the uclgeog codebase
  - python -m pip install --user --upgrade setuptools wheel
  # set up: uses information from env.sh
  #- python setup.py install
  - /bin/bash ./postBuild 
  # sort some edits to the notebook
  - python uclgeog/sort_notebook.py
  - pwd
  - ls
  - cat ${HOME}/.jupyter/jupyter_notebook_config.json
  
# command to run tests
script:
  # this is in test.yml too ... resolve
  - python -c "import gdal" || echo "No gdal!"
