language: python

os: 
  - "linux"
# - windows
# - osx

python:
  - "3.7"
  # for packages on https://repo.anaconda.com/miniconda/
#  - "3.6"      # current default Python on Travis CI
#
#   - "2.7"
#   env: MINI=Miniconda2
#  - "3.4"
#  - "3.5"
#   - "2.7"
#  - "3.4"
# - "3.5"
# conda from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html

env: MINI="Miniconda3";
  MINI_ARCH="x86_64";
  MINI_OS="Linux";
  
before_install:
  # no support for python 2 here
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      # use apt-get for unix packages
      sudo apt update; 
    fi

install:
  # system requirements defined in apt.txt b ut also works for brew
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cat apt.txt | xargs sudo apt-get install; fi
    
  # download miniconda into $HOME/miniconda
  - wget https://repo.continuum.io/miniconda/${MINI}-latest-${MINI_OS}-${MINI_ARCH}.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # set up: uses information from meta.yaml
  - python setup.py install 
  # Replace dep1 dep2 ... with your dependencies
  # python=$TRAVIS_PYTHON_VERSION
  - conda env create -n uclgeog --file environment.yml
  - conda activate uclgeog
  - conda config --add channels proflewis
 
  # make the uclgeog codebase
  - python setup.py install
  - /bin/bash ./postBuild 
  # now put some fixes in ${HOME}/.jupyter/jupyter_notebook_config.json
  # the fix configs are stored in
  - python uclgeog/_sort_notebook.py
  - pwd
  - ls
  - cat ${HOME}/.jupyter/jupyter_notebook_config.json
# command to run tests
script:
  # this is in test.yml too ... resolve
  - python -c "import uclgeog"
