package:
  name:    uclgeog_msc
  version: 1.0.10

source:
  git_rev: 1.0.0
  git_url: https://github.com/UCL-EO/uclgeog_msc_core

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python>=3.8
    - setuptools

  run:
    - python

test:
  imports:
    - uclgeog_msc

about:
  home: https://github.com/UCL-EO/uclgeog_msc_core
