package:
  name:    uclcodebase
  version: 1.0.0

source:
  git_rev: 1.0.0
  git_url: https://github.com/UCL-EO/uclcodebase_core

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python>=3.7
    - setuptools

  run:
    - python

test:
  imports:
    - uclcodebase

about:
  home: https://github.com/UCL-EO/uclcodebase_core
