package:
  name:    uclgeog_msc
  version: 1.0.10

source:
  git_rev: 1.0.0
  git_url: https://github.com/UCL-EO/uclgeog_msc_core

requirements:
  build:
    noarch: generic
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - uclgeog_msc

about:
  home:
