name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'workflow_dispatch'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'trier'
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - name: 'noname_push'
      if: github.event.inputs.name != 'workflow_dispatch'
      run: echo "Hello ${{ github.event.inputs.name }}"
  
    - name: 'noname_manual'
      if: github.event.inputs.name == 'workflow_dispatch'
      run: echo "Hello ${{ github.event.inputs.name }}"

