name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'Update Docker'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.inputs.name }}"
        
    - name: 'noname_push'
      if: github.event.inputs.name != 'Update Docker'
      run: echo "Hello ${{ github.event.inputs.name }}"
  
    - name: 'noname_manual'
      if: github.event.inputs.name == 'Update Docker'
      run: echo "Hello ${{ github.event.inputs.name }}"

