name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'Update Docker'
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  system:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.inputs.name }}"

  docker:
    needs: system
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      if: github.event.inputs.name == 'Update Docker'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: 'not manual action'
      if: github.event.inputs.name != 'Update Docker'
      run: echo "Do a manual trigger set to 'Update Docker'"
    - name: 'Make docker'
      # docker update only on manual at the momnent
      if: github.event.inputs.name == 'Update Docker'
      uses: machine-learning-apps/repo2docker-action@0.2
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "proflewis/uclgeog"
        NOTEBOOK_USER: "uclgeog"
        #BINDER_CACHE: true
        #PUBLIC_REGISTRY_CHECK: true
      env:
        GIT_DISCOVERY_ACROSS_FILESYSTEM: true
        FIRST_NAME: Moto
        LAST_NAME: Moto
        HERESHOWYOUSPELLIT:: M-O-T-O M-O-T-O
