name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: 'noname'
      if: github.event != 'push'
      run: echo ${{github.event}}
  
    - name: 'noname'
      if: github.event == 'workflow_dispatch'
      run: echo ${{github.event.inputs.name}}

