name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'workflow_dispatch'
  push:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'push'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'trier'
      run: "Hello ${{ github.event.inputs.name }}"
      
    - name: 'noname_push'
      if: ${{github.event.inputs.name}} == 'push'
      run: "Hello ${{ github.event.inputs.name }}"
  
    - name: 'noname_manual'
      if: github.event.inputs.name == 'workflow_dispatch'
      run: "Hello ${{ github.event.inputs.name }}"

