name: test-flow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    name: echo 1      
    - run:
        echo "${{ github.event.inputs.name }}"
        
    name: echo 2   
    - run:
        echo "${{ github.event.inputs.name }}"
        
    name: err
    if: github.event == 'workflow_dispatch'
    - run:
        pwd
        
    name: err2
    if: github.event != 'workflow_dispatch'
    - run:
        ls       
