name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
  push:
    inputs:
      name:
        description: 'pusher'
        required: true
        default: 'Test pusher'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: 'noname_push'
      if: github.event == 'push'
      run: echo github.workflow
  
    - name: 'noname_manual'
      if: github.event == 'workflow_dispatch'
      run: echo github.job

