name: test-flow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run:
        echo "${{ github.event.inputs.name }}"
        echo github.event
