name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'Update Docker'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.inputs.name }}"

    - name: checkout files in repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: 'noname_push'
      if: github.event.inputs.name != 'Update Docker'
      run: echo "Hello ${{ github.event.inputs.name }}"
  
    - name: 'noname_manual'
      if: github.event.inputs.name == 'Update Docker'
      uses: machine-learning-apps/repo2docker-action@0.2
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "proflewis/uclgeog_msc"
        NOTEBOOK_USER: "msc_ucl"

