name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run:
        echo "${{ github.event.inputs.name }}"
    - run:
        echo "${{ github.event.inputs.name }}"
    if: github.event == 'workflow_dispatch'
    uses: actions/github-script@v1   
    id: set-result
    with:
      script: return "Hello!"
      result-encoding: string
      run: echo "${{steps.set-result.outputs.result}}"
