name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Test'
  pull_request:
    types: [opened, reopened]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - if: github.event == 'pull_request'
      run: echo "hello world"
