name: upload-to-dockerhub

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Update Docker'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.inputs.name }}"
        echo github.event

    - name: checkout files in repo
      if: github.event != 'workflow_dispatch'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
#    - name: checkout files in repo
#      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      if: github.event != 'workflow_dispatch'
      uses: machine-learning-apps/repo2docker-action@0.2
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_TAG: ${{ github.event.pull_request.head.ref }}
        NO_PUSH: false
        NO_GIT_PUSH: false
        IMAGE_NAME: "proflewis/uclgeog_msc"
        NOTEBOOK_USER: "msc_ucl"
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
